---
title: "EDA"
output: pdf_document
date: "2025-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

suppressMessages(library(tidyverse))
library(lattice)
data <- read.csv()

```
```{r}

## Convert to structured data frame

data <- as_tibble()
summarize()
job_title <- data$Job.Title

```

```{r}

## Job Titles Distribution

bar_plot <- ggplot(data) +
  geom_bar(mapping = aes(x = job_title))

data %>% 
  count(job_title)

## Certification Distribution

ggplot(data) +
  geom_bar(mapping = aes(x = Cert.Area.List))
    data %>% 
      count(Cert.Area.List)

## Civil Service Test Distribution

ggplot(data) +
  geom_bar(mapping = aes(x = Civil.Service.Test))
    school_front %>% 
      count(Civil.Service.Test)

## School District Distribution

ggplot(data) +
  geom_bar(mapping = aes(x = Currently.Employed.District))
    data %>% 
      count(Currently.Employed.District)

## Law Conviction Distribution

ggplot(data) +
  geom_bar(mapping = aes(x = Law.Conviction, na.rm = TRUE))
    data %>% 
      count(Law.Conviction)

## Job Type Distribution

ggplot(data) +
  geom_bar(mapping = aes(x = Teacher...Admin.Positions))
    school_front %>% 
      count(Teacher...Admin.Positions)

## Full-time or Part-time

ggplot(data) +
  geom_bar(mapping = aes(x = Employment.Status.Interests))

## Applicant City Distribution 

ggplot(data) +
  geom_bar(mapping = aes(x = Permanent.City))
    data %>% 
      count(Permanent.City)

## Determine which platforms are most effective
data$How.did.you.hear.about.our.district...job.

```

```{r}

## Distribution Check (Continuous = Histogram)

dates <- structured_data$Job.Deadline

years_experience <- school_front_data$Private.Years

ggplot(structured_data) +
  geom_histogram(mapping = aes(x = years_experience))


## ggplot(structured_data) +
  ## geom_histogram(mapping = aes(x = dates, binwidth = 0.5))

## Numerics
GPA <- na.omit(school_front$Under.Graduate.All.Courses.GPA)

```

```{r}

## Using binwidth (jobs that have few vs. many candidates)

small_subgroups <- structured_data %>% 
  filter(Candidates.Total.Count < 5)

var(small_subgroups) ## Least popular jobs

medium_subgroups <- structured_data %>% 
  filter(Candidates.Total.Count < 10)

medium_subgroups


large_subgroups <- structured_data %>% 
  filter(Candidates.Total.Count > 15)

large_subgroups ## Most popular jobs

```

```{r}

## Clustering Effects (reveal sub-groups)

ggplot(data = small_subgroups, mapping = aes(x = )) +
  geom_histogram(binwidth = 0.01)

```

```{r}

## Replacing the unusual values with missing values

 school_front <- school_front %>% 
  mutate(y = ifelse(y < 3 | y > 20, NA, y))

```

```{r}

## Boxplots (identify outliers)

box_plots <- ggplot(data = structured_data, mapping = aes(x = Candidates.Total.Count, y = Pay.Scale)) +
  geom_boxplot()

```

```{r}

## Scatterplot Distribution

scatter_plot <- ggplot(data = structured_data) + 
  geom_point(mapping = aes(x = Candidates.Total.Count, y = Pay.Scale))

```

```{r}

## Parsing

pay.scale <- parse_number(structured_data$Pay.Scale)
typeof(pay.scale)
sd(pay.scale)
var(pay.scale)

```

```{r}

## Replacement

x <- c("Per contract", 
       "Based on experience and demonstrated abilities",
       "Negotiable")

## With str_replace_all() you can perform multiple replacements by supplying a named vector

str_replace_all(x, c("Per contract" = "Not a number",
"Based on experience and demonstrated abilities" = "NA",
"Negotiable" = "This still isn't a number"))

```

```{r}

x <- structured_data$Pay.Scale

str_replace_all(x, c("Per contract" = "Not a number",
                     "Based on experience and demonstrated abilities" = "NA",
                     "Negotiable" = "This still isn't a number"))

```

```{r}

## Arrange the data

date <- structured_data$Tracker.Date
title <- structured_data$Job.Title
arrange(structured_data, date)

## Numeric Variables

years_experience <- wincap_data$Private.Years
GPA <- wincap_data$Under.Graduate.All.Courses.GPA
service_years <- school_front$Public.Years
cor.test(service_years, years_experience)

```

```{r}

sorting <- select(structured_data, starts_with("Newark"))

```


